#ifndef _TW_METRONOME_H_
#define _TW_METRONOME_H_

#include "tw/core/twtypes.h"
#include "tw/events/twtempomap.h"
#include "tw/playback/twliveplan.h"

#include <atomic>
#include <cstdint>
#include <vector>

// THE METRONOME (proposal 21 L5, design D1/D2).
//
// The click is a LIVE-LANE SOURCE — a `twLiveInputSource` on a synthetic
// "metronome" plan track that joins the closure at the output with no
// processors and unity gain — and it is NEVER a component in the frozen graph.
// Two consequences, and both are the point:
//
//   * a RENDER never has one. `SLiveMonitor::suspendForRender()` drops every
//     lane for the duration of a render, so a project rendered with the
//     metronome on is byte-identical to the same project rendered with it off
//     (gate: `metronome_render_identity.qxa`). A click that lived in the graph
//     would have to be excluded from the render by a special case, and every
//     special case is a place the exclusion can be forgotten;
//   * it is generated BY POSITION, from the block position the pump hands to
//     `pull()`, out of an IMMUTABLE tempo/signature snapshot. There is no
//     "next click" cursor to get out of step with a seek, a loop wrap or a
//     count-in that starts before frame 0: the click at beat k is at
//     `frameOfBeat(k)` whatever order the blocks arrive in, and a click that
//     straddles a block boundary is finished by the next block because both
//     blocks compute the same answer for it.
//
// THREADING. `pull()` runs on the pump thread. It allocates nothing (the two
// click waveforms are rendered once, in the constructor), takes no lock, and
// touches no Qt. The snapshot is const after construction: a tempo or
// time-signature edit builds a NEW source and republishes the plan, which is
// the same discipline the plan's gain envelope and channel map follow.

struct twMetronomeConfig {
    // THE tempo authority (proposal 37 D2), snapshotted. Carries the time
    // signature too, so "how many beats in a bar" and "how long is a beat"
    // come from one object and cannot disagree.
    twTempoMap tempo;
    int        sampleRate = 48000;

    // Linear amplitude of an ordinary beat, and of the accented one (beat 1 of
    // a bar). Both are absolute, not a ratio, so a case can assert the accent
    // ladder without knowing an internal multiplier. The RATIO between them is
    // 1.0 / 0.7 by spec: `SLiveMonitor::ensureMetronome` sets accentLevel from
    // `SOpt::MetronomeLevel` directly and beatLevel to 0.7 of it, so these two
    // defaults are what a caller gets who builds a twMetronomeConfig without
    // going through the app (a unit test, `metronome_test`).
    float beatLevel   = 0.7f;
    float accentLevel = 1.0f;

    // The two pitches, and how long a click lasts. Downbeat 2 kHz, every other
    // beat 1 kHz - the two are far enough apart to tell the accent by EAR, not
    // just by level. 20 ms is short enough that two beats at 300 BPM (200 ms
    // apart) are unambiguously separate events and long enough to be audible
    // on a small speaker.
    double beatHz    = 1000.0;
    double accentHz  = 2000.0;
    double clickMs   = 20.0;

    // Project frame of bar 1, beat 1. Zero for every project today; the field
    // exists so a future bar-1-elsewhere does not need a second code path.
    offset_t gridOrigin = 0;

    // false == every beat is an ordinary one (no bar accent).
    bool accentBars = true;

    // THE ACTIVE RANGE, half-open [rangeStart, rangeEnd), in project frames.
    // Unlimited by default; a COUNT-IN sets it to [locator - N bars, locator)
    // so the click stops at exactly the frame recording begins.
    //
    // It is a RANGE rather than a "stop clicking now" call for the same reason
    // everything else here is by position: the pump renders one to two blocks
    // AHEAD of the RT, so by the time the app noticed the count-in was over,
    // the downbeat click past its end would already be in the ring. A range
    // makes "exactly N bars of clicks" a property of the waveform instead of a
    // race between two threads.
    static constexpr offset_t kNoLimit = (offset_t) 0x7FFFFFFFFFFFFFFFll;
    offset_t rangeStart = -kNoLimit;
    offset_t rangeEnd   =  kNoLimit;

    bool operator==( const twMetronomeConfig &o ) const
    {
        return tempo == o.tempo && sampleRate == o.sampleRate
               && beatLevel == o.beatLevel && accentLevel == o.accentLevel
               && beatHz == o.beatHz && accentHz == o.accentHz
               && clickMs == o.clickMs && gridOrigin == o.gridOrigin
               && accentBars == o.accentBars && rangeStart == o.rangeStart
               && rangeEnd == o.rangeEnd;
    }
    bool operator!=( const twMetronomeConfig &o ) const { return !( *this == o ); }
};

class twMetronomeSource : public twLiveInputSource
{
public:
    explicit twMetronomeSource( const twMetronomeConfig &cfg );

    // ADDS the click into `out` (the pump zeroes the track's buffer first, so
    // add and write are the same thing there, and adding is the safe reading
    // of "fill"). Always returns `frames`: a metronome cannot fall short, and
    // reporting less would count a pump shortfall for silence between beats.
    std::size_t pull( float *const *out, std::size_t channels,
                      std::size_t frames, offset_t pos ) override;

    // --- the grid, exactly (also the unit test's whole surface) -------------

    /// Project frame of beat `k`, counted from `gridOrigin`. Exact: the beat
    /// length is a reduced rational and this is one floored division, so beat
    /// k is never the accumulation of k roundings. Negative k is legal — a
    /// count-in runs before the locator and may run before frame 0.
    offset_t frameOfBeat( std::int64_t k ) const;
    /// The index of the last beat at or before `pos` (floor).
    std::int64_t beatAtOrBefore( offset_t pos ) const;
    /// Is beat `k` the accented one (beat 1 of a bar)?
    bool isAccent( std::int64_t k ) const;

    std::int64_t beatsPerBar()  const { return beatsPerBar_; }
    length_t     clickFrames()  const { return (length_t) clickFrames_; }
    /// Frames per bar, floored — what a count-in of N bars costs.
    offset_t     barFrames()    const { return frameOfBeat( beatsPerBar_ )
                                               - frameOfBeat( 0 ); }
    const twMetronomeConfig &config() const { return cfg_; }

    /// Clicks whose first sample this source has written. Diagnostics only.
    std::uint64_t clicksEmitted() const
    { return clicks_.load( std::memory_order_relaxed ); }

private:
    void buildClick_( std::vector<float> &dst, double hz, float level ) const;

    twMetronomeConfig cfg_;
    // The beat length as a REDUCED rational, so `frameOfBeat` is exact.
    std::int64_t beatNum_ = 1, beatDen_ = 1;
    std::int64_t beatsPerBar_ = 4;
    std::size_t  clickFrames_ = 0;
    std::vector<float> accentWave_, beatWave_;
    std::atomic<std::uint64_t> clicks_{ 0 };
};

#endif  // _TW_METRONOME_H_
