#!/usr/bin/env bash
#
# ci/clean.sh — throw away build output without throwing away the checkout.
#
#     ./ci/clean.sh          # smaragd/build/, the tree ci/build.sh owns
#     ./ci/clean.sh --all    # ...plus stray build trees and smaragd/test-output/
#     ./ci/clean.sh -n       # print what would go, remove nothing
#
# A clean rebuild is `./ci/clean.sh && ./ci/build.sh`, which is what ./rebuild.sh
# used to be; `./ci/build.sh --clean` is the same thing in one command.
#
# THERE IS NO `git clean -xfd` HERE, AND THERE MUST NOT BE. This checkout holds
# two things that are ignored by git and expensive-to-impossible to get back:
#
#   * smaragd/third_party/asiosdk/ — the Steinberg ASIO SDK. Licensed and NOT
#     redistributable, so it is a MANUAL drop-in: a human downloads a zip from
#     steinberg.net and unpacks it there. `git clean` deletes it silently and
#     the next Windows build quietly loses its ASIO backend.
#   * the submodule checkouts under smaragd/third_party/ (clap, vst3), which
#     `git clean -xfd` in a submodule-bearing repo will also take.
#
# Both are why this script removes a NAMED LIST and never a pattern of
# "everything untracked".
set -euo pipefail

CI_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$CI_DIR/.." && pwd)"

DRY=""
WANT_ALL=""

while [ $# -gt 0 ]; do
    case "$1" in
        -n|--dry-run) DRY="yes"; shift ;;
        --all)        WANT_ALL="yes"; shift ;;
        -h|--help)    sed -n '2,8p' "$0"; exit 0 ;;
        *) echo "usage: ci/clean.sh [--all] [-n]" >&2; exit 2 ;;
    esac
done

say()  { printf '\n=== %s ===\n' "$*"; }
note() { printf '  %s\n' "$*"; }

# Collected first, acted on second, so -n and the real run cannot disagree about
# what is about to happen.
TARGETS=()
add() { [ -e "$1" ] && TARGETS+=("$1") || true; }

add "$REPO_DIR/smaragd/build"

if [ -n "$WANT_ALL" ]; then
    # Stray trees from an out-of-tree or hand-rolled configure. These are the
    # ones that were TRACKED for four months because .gitignore named the
    # hyphen form and not the underscore one (#219), so they do accumulate here
    # in practice and nothing else cleans them.
    for d in "$REPO_DIR"/build-*/ "$REPO_DIR"/build_*/ \
             "$REPO_DIR"/smaragd/build-*/ "$REPO_DIR"/smaragd/build_*/; do
        [ -d "$d" ] && add "${d%/}"
    done
    # Regenerated by every suite run: renders, plus screenshots that capture the
    # whole desktop because the screenshot action grabs the root window.
    add "$REPO_DIR/smaragd/test-output"
fi

if [ "${#TARGETS[@]}" -eq 0 ]; then
    say "Nothing to remove"
    note "Already clean (or the paths do not exist yet)."
    exit 0
fi

say "$([ -n "$DRY" ] && echo "Would remove" || echo "Removing")"
for t in "${TARGETS[@]}"; do
    sz="$(du -sh "$t" 2>/dev/null | cut -f1 || echo '?')"
    printf '  %-6s %s\n' "$sz" "${t#"$REPO_DIR"/}"
done

if [ -n "$DRY" ]; then
    say "Dry run"
    note "Nothing was removed. Re-run without -n."
    exit 0
fi

for t in "${TARGETS[@]}"; do rm -rf -- "$t"; done

say "Kept"
note "smaragd/third_party/asiosdk — the licensed manual drop-in"
note "every submodule checkout — no git clean, no deinit"
[ -z "$WANT_ALL" ] && note "smaragd/test-output (pass --all to drop it as well)"
say "Done"
note "Next: ./ci/build.sh"
